services:
  db:
    image: postgres:13.21-alpine
    container_name: kenshu_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - kenshu_app
  nginx:
    image: nginx:stable
    container_name: kenshu_nginx
    ports:
      - 3000:80
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-fpm
    networks:
      - kenshu_app
  php-fpm:
    container_name: kenshu_php-fpm
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db
    networks:
      - kenshu_app
  valkey:
    image: valkey/valkey:latest
    container_name: kenshu_valkey
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    networks:
      - kenshu_app

volumes:
  postgres_data:
  valkey_data:

networks:
  kenshu_app:
